FROM python:3.11-slim

WORKDIR /app

COPY requirements.mlflow.txt .
RUN pip install --upgrade pip && pip install -r requirements.mlflow.txt

COPY train_model.py .
COPY data/ ./data

CMD ["python", "train_model.py"]