# Dockerfile.streamlit
FROM python:3.11-slim

WORKDIR /app

COPY requirements.streamlit.txt .
RUN pip install --upgrade pip && pip install -r requirements.streamlit.txt

# Vérification de version MLflow
RUN python -c "import mlflow; print('✅ MLflow installé - version :', mlflow.__version__)"

COPY ./streamlit ./streamlit
COPY ./data ./data

EXPOSE 8501

CMD ["streamlit", "run", "streamlit/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
