# Dockerfile.api
FROM python:3.11-slim

WORKDIR /app

COPY requirements.api.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.api.txt

COPY ./api ./api
COPY ./data ./data

EXPOSE 8000

CMD ["uvicorn", "api.main2:app", "--host", "0.0.0.0", "--port", "8000"]
